SiliconMVC/Controllers/SiteSettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace SiliconMVC.Controllers
{
    public class SiteSettingsController : Controller
    {
        [HttpPost]
        public IActionResult ConsentCookies()
        {
            var option = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60),
                HttpOnly = true,
                Secure = true
            };

            Response.Cookies.Append("CookieConsent", "true", option);
            return Ok();
        }
    }
}

SiliconMVC/Views/Shared/Sections/_AccountAsidePartial.cshtml
@* KRÄVER VIEWMODEL *@

<div class="avatar-box">
    <img class="avatar-img" src="~/img/uploads/profiles/@(Model.ProfileInfo!.ProfileImg)" alt="">
    <div class="change-avatar">
        <img src="~/img/icons/bx-refresh.svg" alt="">
    </div>
</div>
<div class="short-info-box">
    <p class="h5">@($"{Model.ProfileInfo!.FirstName} {Model.ProfileInfo.LastName}")</p>
    <p class="text-m">@($"{Model.ProfileInfo.Email}")</p>
</div>
<div class="buttons-box">
    <button class="btn-theme" asp-controller="User" asp-action="Details">
        <i class="fas fa-cog"></i>
        <p>Account Details</p>
    </button>
    <a type="button" class="btn-white" asp-controller="Auth" asp-action="Signout">
        <i class="fa-solid fa-arrow-right-from-bracket"></i>
        <p>Sign out</p>
    </a>
</div>

SiliconMVC/Views/Shared/Sections/_AccountDetailsPartial.cshtml
@model UserDetailsViewModel
@inject UserManager<UserEntity> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}

<section class="account-details w-full d-flex center">
    <div class="container w-max">
        <aside class="side">
            @if (user != null)
            {
                <div class="avatar-box">
                    <img class="avatar-img" src="~/img/uploads/profiles/@(user.ProfileImg)" alt="@user.FirstName @user.LastName" />

                    <form class="change-avatar" enctype="multipart/form-data" method="post" asp-action="UploadProfileImage" asp-controller="User">
                        <input id="fileUploader" type="file" name="file" hidden/>
                        <label for="fileUploader">
                            <img src="~/img/icons/bx-refresh.svg" alt="">
                        </label>
                    </form>

                </div>
                <div class="short-info-box">
                    <p class="h5">@($"{user.FirstName} {user.LastName}")</p>
                    <p class="text-m">@($"{user.Email}")</p>
                </div>
                <div class="buttons-box">
                    <button class="btn-theme" asp-controller="User" asp-action="Details">
                        <i class="fas fa-cog"></i>
                        <p>Account Details</p>
                    </button>
                    <a type="button" class="btn-white" asp-controller="Auth" asp-action="Signout">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                        <p>Sign out</p>
                    </a>
                </div>
            }
        </aside>

        <div class="details">
            <h1>Account details</h1>
            @* <div>
                @TempData["StatusMessage"]
            </div> *@
            <partial name="~/Views/Shared/Forms/_UserBasicInfoForm.cshtml" model="Model" />
            <partial name="~/Views/Shared/Forms/_UserAddressForm.cshtml" model="Model"/>
        </div>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_BreadcrumbsPartial.cshtml
<section class="breadcrumbs w-full d-flex center">
    <div class="container w-max d-flex">
        <i class="fa-solid fa-house"></i>
        <p><a href="">Home</a> » <a href="" class="active">Courses</a></p>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_CookieConsent.cshtml
@if (Context.Request.Cookies["CookieConsent"] == null)
{
    <section id="cookie-consent" class="w-full d-flex center">
        <div class="container w-max d-flex center">
            <span class="text-m">This website uses cookies to improve the user experience</span>
            <button class="btn btn-gray" onClick="acceptCookieConsent()">Accept</button>
        </div>
    </section>

    <script>
        function acceptCookieConsent() {
            document.getElementById('cookie-consent').style.display = 'none'

        @* EASY *@
        @* fetch(`\sitesettings\consentcookies`) *@

        @* HARD *@
            fetch('@Url.Action("ConsentCookies", "SiteSettings")', {
                method: 'POST',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
        }
    </script>
}

SiliconMVC/Views/Shared/Sections/_CoursesPartial.cshtml
@model CourseViewModel

<section class="courses w-full d-flex center">
    <div class="container w-max d-flex column">
        <div class="heading-box">
            <h1>Courses</h1>
            <div class="input-box">
                <form id="category-filter" action="">
                    <select list="categories" placeholder="All categories">
                        <option>All categories</option>
                        <option>Chrome</option>
                        <option>Edge</option>
                        <option>Firefox</option>
                        <option>Opera</option>                        
                        <option>Safari</option>
                    </select>
                </form>
                <form id="search" action="">
                    <input type="text" placeholder="Search Courses">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </form>
            </div>
        </div>
        <div class="grid-box">
            @if (Model.Courses != null)
            {
                foreach (var course in Model.Courses)
                {
                    <div class="grid-item">
                        <a asp-action="Index" asp-controller="Course" asp-route-id="@course.Id" class="content">
                            <img src="~/img/courses/@course.ImageUrl" alt="Image for @course.Title">
                            <div class="text-box">
                                <p class="h5">@course.Title</p>
                                <p class="text-s">By @course.Author</p>
                                @if (course.DiscountPrice >= 0)
                                {
                                    <p><span class="text-l price sale-new">$@Math.Round(course.DiscountPrice, 2)</span> <span class="text-l price sale-old">$@Math.Round(course.Price, 2)</span></p>
                                }
                                else
                                {
                                    <p class="text-l price">$@Math.Round(course.Price, 2)</p>
                                }
                                <div class="info-box">
                                    <p class="text-s hours">@course.Hours hours</p>
                                    <p class="text-s rating">@course.LikesInPercent()% (@course.TotalBuysInK()K)</p>
                                </div>
                            </div>
                        </a>
                        @if (course.BestSeller)
                        {
                            <div class="text-s tag">Best Seller</div>
                        }
                        <button class="bookmark">
                            <i class="fa-regular fa-bookmark"></i>
                        </button>
                    </div>
                }
            }
        </div>
        <div class="pagination-box">

        </div>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_CreateAccountPartial.cshtml
@model SignUpViewModel

<section class="create-account-form w-full d-flex center">
    <div class="container d-flex column">
        <partial name="~/Views/Shared/Forms/_UserCreateAccountForm.cshtml" model="Model" />
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_DownloadourappPartial.cshtml
<section class="downloadourapp w-full d-flex center">
    <div class="container w-max d-flex">
        <img src="~/img/app.png" alt="">
        <div class="content d-flex column">
            <h2 class="h1">Download our app for any devices</h2>
            <ul>
                <li>
                    <p class="text-m">App Store</p>
                    <div class="score">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                    </div>
                    <div class="box">
                        <div class="text">
                            <h3 class="h4">Editor's choice</h3>
                            <p class="text-m">rating 4.7, 187K+ reviews</p>
                        </div>
                        <a href="">
                            <img src="~/img/appstore.svg" alt="">
                        </a>
                    </div>
                </li>
                <li>
                    <p class="text-m">Google Play</p>
                    <div class="score">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                        <img src="~/img/icons/star.svg" alt="">
                    </div>
                    <div class="box">
                        <div class="text">
                            <h3 class="h4">App of the day</h3>
                            <p class="text-m">rating 4.8, 30K+ reviews</p>
                        </div>
                        <a href="">
                            <img src="~/img/googleplay.svg" alt="">
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_HeroPartial.cshtml
<section class="hero w-full d-flex center">
    <div class="container w-max">
        <div class="content w-half d-flex column center">
            <h1 class="d4">Task management assistant you gonna love</h1>
            <p class="text-lg">We offer you a new generation of task management system. Plan, manage & track all your tasks in one flexible tool.</p>
            <a class="btn-theme">Get started for free</a>
            <p class="h6">Largest companies use our tool to work efficiently</p>
            <div class="brands">
                <img src="~/img/logoipsum1.svg" alt="">
                <img src="~/img/logoipsum2.svg" alt="">
                <img src="~/img/logoipsum3.svg" alt="">
                <img src="~/img/logoipsum4.svg" alt="">
            </div>
        </div>

        <img class="hero-img" src="~/img/hero.png" alt="">
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_IntegratetoptoolsPartial.cshtml
<section class="integratetoptools w-full d-flex center">
    <div class="container w-max d-flex column center">
        <h2 class="h1">Integrate top work tools</h2>
        <p class="text-lg ingress">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin volutpat mollis egestas. Nam luctus facilisis ultrices. Pellentesque volutpat ligula est. Mattis fermentum, at nec lacus.</p>
        <div class="grid">
            <div class="grid-item">
                <img src="~/img/icons/Google.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/Zoom.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/brand1.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/Gmail.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/Trello.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/Mailchimp.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/Dropbox.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
            <div class="grid-item">
                <img src="~/img/icons/Evernote.svg" alt="">
                <p class="text-m">Lorem magnis pretium sed curabitur nunc facilisi nunc cursus sagittis.</p>
            </div>
        </div>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_LightdarkswitchPartial.cshtml
<section class="lightdarkswitch w-full d-flex center">
    <div class="container w-max d-flex center">
        <img src="~/img/Slider.png" alt="">
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_ManageyourworkPartial.cshtml
<section class="manageyourwork w-full d-flex center">
    <div class="container w-max d-flex center">
        <img src="~/img/dashboard.png" alt="">
        <div class="content">
            <h2>Manage your work</h2>
            <ul>
                <li>Powerful project management</li>
                <li>Transparent work management</li>
                <li>Manage work & focus on the most important tasks</li>
                <li>Track your progress with interactive charts</li>
                <li>Easiest way to track time spent on tasks</li>
            </ul>
            <a class="btn-theme">
                <span>Learn more</span>
                <i class="fa-solid fa-arrow-right"></i>
            </a>
        </div>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_NewsletterPartial.cshtml
@model SubscribeViewModel

<section id="newsletter" class="newsletter w-full d-flex center">
    <div class="container d-flex column">
        <div class="heading">
            <h2 class="h1">Don't want to miss anything?</h2>
            <img src="~/img/arrows.svg" alt="">
        </div>
        
        <partial name="~/Views/Shared/Forms/_NewsletterForm.cshtml" model="Model" />
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_WhatugetPartial.cshtml
<section class="whatuget w-full d-flex center">
    <div class="container w-max d-flex column center">
        <h2>What do you get with our tool?</h2>
        <p>Make sure all your tasks are organized so you can set the priorities and focus on important.</p>
        <div class="grid">
            <a href="#" class="d-flex column center">
                <img src="~/img/icons/comment_on_tasks.svg" alt="">
                <p class="h5">Comments on Tasks</p>
                <p class="text-m">Id mollis consectetur congue egestas egestas suspendisse blandit justo.</p>
            </a>
            <a href="#" class="d-flex column center">
                <img src="~/img/icons/task_analytics.svg" alt="">
                <p class="h5">Task Analytics</p>
                <p class="text-m">Non imperdiet facilisis nulla tellus Morbi scelerisque eget adipiscing vulputate.</p>
            </a>
            <a href="#" class="d-flex column center">
                <img src="~/img/icons/multiple_assignees.svg" alt="">
                <p class="h5">Multiple Assignees</p>
                <p class="text-m">A elementum, imperdiet enim, pretium etiam facilisi in aenean quam mauris.</p>
            </a>
            <a href="#" class="d-flex column center">
                <img src="~/img/icons/notifications.svg" alt="">
                <p class="h5">Notifications</p>
                <p class="text-m">Diam, suspendisse velit cras ac. Lobortis diam volutpat, eget pellentesque viverra.</p>
            </a>
            <a href="#" class="d-flex column center">
                <img src="~/img/icons/sections_subtasks.svg" alt="">
                <p class="h5">Sections & Subtasks</p>
                <p class="text-m">Mi feugiat hac id in. Sit elit placerat lacus nibh lorem ridiculus lectus.</p>
            </a>
            <a href="#" class="d-flex column center">
                <img src="~/img/icons/data_security.svg" alt="">
                <p class="h5">Data Security</p>
                <p class="text-m">Aliquam malesuada neque eget elit nulla vestibulum nunc cras.</p>
            </a>
        </div>
    </div>
</section>

SiliconMVC/Views/Shared/Sections/_WorkWithUsPartial.cshtml
<section class="workwithus w-full d-flex center">
    <div class="container w-max d-flex">
        <div class="text">
            <p class="text-lead">Ready to get started?</p>
            <h2 class="h1">Take your <span>skills</span> to the next level</h2>
            <button class="btn-theme">Work with us</button>
        </div>

        <img src="~/img/desk.svg" alt="">
    </div>
</section>